Main_Website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('receive/', include('receive.urls')),
    path('SimpleApp/', include('SimpleApp.urls')),
	path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

SimpleApp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
	
	# ex: /app/id/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /app/id/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /app/id/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
	path('', views.index, name='index'),
	path('<int:id_soalan>/', views.detail, name='detail'),
	path('<int:id_soalan>/results/', views.results, name='results'),
	path('<int:id_soalan>/undi/', views.undi, name='undi'),
]

receive/urls.py
from django.urls import path

from . import views


urlpatterns = [
	path('', views.masuk_input, name='masuk_input'),
]

SimpleApp/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Soalan(models.Model):
	ayat_soalan = models.CharField(max_length=200)
	tarikh_soalan = models.DateTimeField('date published')
	def __str__(self):
		return self.ayat_soalan
	def soalan_baru(self):
		return self.tarikh_soalan >= timezone.now() - datetime.timedelta(days=1)


class Pilihan(models.Model):
	soalan = models.ForeignKey(Soalan, on_delete=models.CASCADE)
	ayat_pilihan = models.CharField(max_length=200)
	undian = models.IntegerField(default=0)
	def __str__(self):
		return self.ayat_pilihan

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Soalan(models.Model):
	teks_soalan = models.CharField(max_length=200)
	tarikh_soalan = models.DateTimeField('data published')

	def __str__(self):
		return self.teks_soalan

	def baru_ke(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)



class Pilihan(models.Model):
	Soalan = models.ForeignKey(Soalan, on_delete=models.CASCADE)
	teks_pilihan = models.CharField(max_length=200)
	undi = models.IntegerField(default=0)

	def __str__(self):
		return self.teks_pilihan

receive/models.py
from django.db import models

# Create your models here.

SimpleApp/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
from django.template import loader


from .models import Soalan

def index(request):
	return HttpResponse("The Amazing Spiders")


# List kan latest 5 object
def index(request):
	latest_list_soalan = Soalan.objects.order_by('-tarikh_soalan')[:5]
	template = loader.get_template('SimpleApp/index.html')
	context = {
	'latest_list_soalan': latest_list_soalan,
	}
	return HttpResponse(template.render(context, request))


# Setiap page utk setiap elemen: detail, result, undi, based on object id
def detail(request, question_id):
	return HttpResponse("Sekarang soalan %s." % question_id)

def results(request, question_id):
	response = "Sekarang result untuk soalan %s."
	return HttpResponse(response % question_id)

def vote(request, question_id):
	return HttpResponse("Sekarang undi untuk soalan %s." % question_id)

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader

from .models import Soalan, Pilihan

# Create your views here.
def index(request):
	list_soalan = Soalan.objects.order_by('-tarikh_soalan')[:5]
	template = loader.get_template('polls/index.html')
	context = {
		'list_soalan': list_soalan,
	}
	return HttpResponse(template.render(context, request))

def detail(request, id_soalan):
	soalan = get_object_or_404(Soalan, pk=id_soalan)
	return render(request, 'polls/detail.html', {'soalan': soalan})

def results(request, id_soalan):
	response = "Sekarang results soalan %s."
	return HttpResponse(response % id_soalan)

def undi(request, id_soalan):
	soalan = get_object_or_404(Soalan, pk=id_soalan)
	try:
		dipilih = soalan.choice_set.get(pk=request.POST['pilihan'])
	except (KeyError, Pilihan.DoesNotExist):
		return render(request, 'polls/detail.html', {
			'soalan': soalan,
			'error_message': "Dak awat tak pilih, orang suruh pilih",
		})
	else:
		dipilih.undi += 1
		dipilih.save()
		return HttpResponseRedirect(reverse('polls:results', args=(soalan.id,)))

receive/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def masuk_input(request):
	if request.method == 'GET':
		mesej = request.GET.get('mesej', '')
		return HttpResponse('Mesej anda ialah: ' + mesej)

SimpleApp/templates/SimpleApp/index.html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>My test page</title>
  </head>
  <body>
    {% if latest_question_list %}
      <ul>
      {% for question in latest_question_list %}
        <li><a href="/SimpleApp/{{ Soalan.id }}/">{{ Soalan.ayat_soalan }}</a></li>
      {% endfor %}
      </ul>
    {% else %}
      <p>No polls are available.</p>
    {% endif %}
  </body>
</html>

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>My test page</title>
  </head>
  <body>
	<form action="{% url 'polls:undi' soalan.id %}" method="post">
	{% csrf_token %}
	<fieldset>
		<legend><h1>{{ soalan.teks_soalan }}</h1></legend>
		{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
		{% for pilihan in soalan.choice_set.all %}
			<input type="radio" name="pilihan" id="pilihan{{ forloop.counter }}" value="{{ pilihan.id }}">
			<label for="pilihan{{ forloop.counter }}">{{ pilihan.teks_pilihan }}</label><br>
		{% endfor %}
	</fieldset>
	<input type="submit" value="Undi">
	</form>
  </body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <title>My test page</title>
  </head>
  <body>
	{% if list_soalan %}
		<ul>
		{% for soalan in list_soalan %}
			<li><a href="{% url 'polls:detail' soalan.id %}/">{{ soalan.teks_soalan }}</a></li>
		{% endfor %}
		</ul>
	{% else %}
		<p>No polls are available.</p>
	{% endif %}
  </body>
</html>